"""empty message

Revision ID: 7080ab692946
Revises: 055feff34ec6
Create Date: 2017-03-26 23:18:29.676490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7080ab692946'
down_revision = '055feff34ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_posts_tags_post_id'), 'posts_tags', ['post_id'], unique=False)
    op.create_index(op.f('ix_posts_tags_tag_id'), 'posts_tags', ['tag_id'], unique=False)
    op.create_foreign_key(None, 'posts_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'posts_tags', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_index(op.f('ix_posts_tags_tag_id'), table_name='posts_tags')
    op.drop_index(op.f('ix_posts_tags_post_id'), table_name='posts_tags')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_column('comments', 'email')
    # ### end Alembic commands ###
